guns:
  swagger-open: false              #是否开启swagger (true/false)
  kaptcha-open: true             #是否开启登录时验证码 (true/false)
  file-upload-path: d:/tmp     #文件上传目录(不配置的话为java.io.tmpdir目录)
  spring-session-open: false      #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

beetl:
  resource-auto-check: false       #热加载beetl模板，开发时候用

spring:
  datasource:
    url: jdbc:mysql://你的mysql地址/guns?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: mysql账号
    password: mysql密码
    filters: wall,mergeStat
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  typeAliasesPackage: com.jsnjfz.manage.modular.system.model

log:
  path: /home/service/site/logs

#七牛云
qiniu:
  accessKey: 七牛云访问钥匙
  secretKey: 七牛云密钥
  url: 七牛云桶地址
  bucketName: 七牛云桶名称
  qiniupUrl: http://upload.qiniup.com
  qiniuRsUrl: http://rs.qiniu.com
  qiniuRsfUrl: http://rsf.qiniu.com
  qiniuApifUrl: http://api.qiniu.com
  qiniuVipUrl: http://iovip.qbox.me
  qiniuHostUrl: ai.qiniuapi.com
  qiniuCheckImgUrl: http://ai.qiniuapi.com/v3/image/censor

